name = "Aspiring Hippie"
rol = "Data Analyst | Aspiring Data Scientist| Here Be Dragons"
email = "aspiringhippie3000@gmail.com"
phone = "+ 233 (0)55 643 4203"
birthday = "Feb 26, 1999"
location = "Accra, Ghana"
avatar = "./config/assets/avatars/Aspiring Hippie.png"
username = "Aspiring Hippie" # <-- github user name
googlemaps = "https://www.google.com/maps/place/Mataheko,+Accra/@5.5613636,-0.2580335,15.44z/data=!4m6!3m5!1s0xfdf99d9f2fbe42f:0x9ada4c30f43ae7af!8m2!3d5.5661142!4d-0.2476103!16s%2Fg%2F11btzyygr0?entry=ttu" 
presentation = """
I'm simply HIM ðŸ’ðŸ¿
"""
