name = "Samuel Lartey"
rol = "| Data Analyst |"
email = "sammylartey39@gmail.com"
phone = "+ 233 (0)55 643 4203"
birthday = "Feb 26, 1999"
location = "Accra, Ghana"
avatar = "./config/assets/avatars/Aspiring Hippie.png"
username = "Aspiring Hippie" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15802.570481524942!2d-0.1974306!3d5.5592846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf9084b2b7a773%3A0xbed14ed8650e2dd3!2sAccra%2C%20Ghana!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd" 
presentation = """
Hey there! I'm Samuel Lartey, a data enthusiast based in Accra, Ghana. 

With a background in computer science, I bring a unique blend of technical expertise and creative vision to every project I undertake. Whether I'm deciphering complex datasets or exploring innovative solutions, my passion lies in unraveling the mysteries hidden within data. 

Join me on a journey where insights drive action, and where every challenge presents an opportunity for growth. Let's navigate the world of data together, one discovery at a time.
"""
