[[project]]
title = "Customer Support ETL Pipeline"
category = "Python Programming"
image = "config/assets/projects/CustomerSupport.jpg"
url = "https://github.com/Sammy-Lartey/customer-support-ETL-pipeline"

[[project]]
title = "SMS Spam Detector"
category = "Python Programming"
image = "config/assets/projects/Telecom.jpg"
url = "https://github.com/Sammy-Lartey/Spam-Detector---ML"

[[project]]
title = "Video Game Sales Analysis"
category = "Data Analytics"
image = "config/assets/projects/VideoGames.jpg"
url = "https://github.com/Sammy-Lartey/Data-Analytics-Portfolio/tree/main/Video%20Game%20Data%20Analysis%20Project"

[[project]]
title = "Ecommerce Order Distribution"
category = "Python Programming"
image = "config/assets/projects/Trucks.jpg"
url = "https://github.com/Sammy-Lartey/E-commerce-Order-Distribution-Optimization-"

[[project]]
title = "Telecom Churn Analysis"
category = "Data Analytics"
image = "config/assets/projects/Telecom.jpg"
url = "https://github.com/Sammy-Lartey/Telecom-Customer-Churn"

[[project]]
title = "Chips Sales Analysis (QUANTIUM Virtual Experience Program)"
category = "Data Analytics"
image = "config/assets/projects/Chips.jpg"
url = "https://github.com/Sammy-Lartey/QUANTIUM-Data-Analytics-Virtual-Experience-Program"

[[project]]
title = "Google Trends Analysis"
category = "Data Analytics"
image = "config/assets/projects/Google.jpg"
url = "https://github.com/Sammy-Lartey/Google-Trends-Data-Resampling-and-Visualizing-Time-Series"

[[project]]
title = "Nobel Prize Analysis"
category = "Data Analytics"
image = "config/assets/projects/Nobel.jpg"
url = "https://github.com/Sammy-Lartey/Nobel-Prize-Analysis-"

[[project]]
title = "Password Generator"
category = "Python Programming"
image = "config/assets/projects/Password.jpg"
url = "https://github.com/Sammy-Lartey/simple-password-gen"

[[project]]
title = "Bike Store Dashboard"
category = "Data Visualization"
image = "./config/assets/projects/Viz 1.png"
url = "https://public.tableau.com/app/profile/sammy.lartey/viz/BikeStoreDashboard_16920594543270/Dashboard1"

[[project]]
title = "IMDB Dashboard"
category = "Data Visualization"
image = "./config/assets/projects/Viz 2.png"
url = "https://public.tableau.com/app/profile/sammy.lartey/viz/IMDBDashboard_16898211927910/Dashboard1"

[[project]]
title = "LEGO Set Analysis(REBRICKABLE)"
category = "Data Analytics"
image = "config/assets/projects/LEGO.jpg"
url = "https://github.com/Sammy-Lartey/-LEGO-Set-Analysis-with-Rebrickable-Data"

[[project]]
title = "Film Budget Revenue Analysis"
category = "Data Analytics"
image = "config/assets/projects/Movies.jpg"
url = "https://github.com/Sammy-Lartey/Film-Budget-Revenue-Analysis"

#[[project]]
#title = "DSM."
#category = "Web design"
#image = "./config/assets/projects/project-5.png"
#url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

#[[project]]
#title = "MetaSpark"
#category = "Web design"
#image = "./config/assets/projects/project-6.png"
#url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

#[[project]]
#title = "Summary"
#category = "Web development"
#image = "./config/assets/projects/project-7.png"
#url = "https://github.com/ivansaul/codigo_facilito_downloader"

#[[project]]
#title = "Task Manager"
#category = "Applications"
#image = "./config/assets/projects/project-8.jpg"
#url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

#[[project]]
#title = "Arrival"
#category = "Web development"
#image = "./config/assets/projects/project-9.png"
#url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"
