############## Education config #################
#################################################
[[education]]
title = "Pieran Data Python Programming Bootcamp"
timeline = "October 2022 - December 2022"
description = """
Coursework: Python Basics, Object Oriented Programming in Python, Databases with Python, Advanced Python Modules, 
Python for Data Science and Machine Learning.
"""

[[education]]
title = "Google Data Analytics Professional Certificate"
timeline = "January 2023 - April 2023"
description = """
Coursework: Intro to Data Analytics, Advanced data cleaning, Data analysis with Google Sheets and Microsoft Excel, Data 
analysis with SQL and R programming, Data Visualization with Tableau.
"""

[[education]]
title = "QUANTIUM Data Analytics Virtual Experience Program"
timeline = "March 2024"
description = """
Data preparation and customer analytics, Experimentation and uplift testing Analytics and commercial application using Python 
programming.
"""

[[education]]
title = "Bachelor of Science in Computer Science"
school = "Catholic University College of Ghana"
timeline = "September 2017 — October 2021"
description = """
Relevant Coursework: Data Structures and Algorithms, Critical Thinking, Database Management Systems, Statistical Analysis,
Object Oriented Programming, Data Science and Machine Learning.
"""


############## Experience config ################
#################################################
[[experience]]
title = "Research Personnel"
company = "University of Ghana Medical Center"
timeline = "October 2021 — September 2022"
description = [
  "- Conducted surveys and collected data from over 500 patients using Google Forms and Microsoft Excel. This initiative resulted in a 25% reduction in patient wait times and a 30% increase in patient satisfaction scores.",
  "- Utilized Microsoft Excel to process and visually present datasets of over 1,000 records, leading to a substantial 30% enhancement in data accuracy. This precision not only improved data reliability but also streamlined decision-making processes, which resulted in a 15% improvement in operational efficiency.",
  "- Conducted literature reviews, analyzed research articles, and summarized key findings to guide research studies.",
  "- Coordinated AIDET training programs aimed at enhancing communication and fostering a more patient-centered approach within the organization, which led to a 25% improvement in good staff-patient interactions and a 30% rise in patient satisfaction scores. These initiatives also contributed to a 15% decrease in complaints and a 10% improvement in overall healthcare quality metrics.",
  "- Actively participated in cross-functional collaborations with the Thyroid Ghana Foundation and medical staff to organize awareness campaigns and health screenings, reaching over 1,000 community members."
]

# You can add more experience entries following the same structure:
# [[experience]]
# title = "Title of the experience"
# company = "Company name"
# timeline = "Duration of the experience"
# description = [
#   "Description point 1",
#   "Description point 2",
#   ...
# ]





# [[experience]]
# title = "Art director"
# timeline = "2013 — 2015"
# description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

# [[experience]]
# title = "Creative director"
# timeline = "2015 — Present"
# description = "Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Data Analysis"
value = "70%"

[[skill]]
title = "Data Visualization"
value = "70%"

[[skill]]
title = "Programming"
value = "70%"

[[skill]]
title = "Database Management"
value = "65%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "90%"

[[language]]
title = "French"
value = "50%"
